Applicative validation
active-group/active-clojure pull request #43
Opened 2022-05-25 07:49 UTC by neshtea

This pull requests adds the `active.clojure.validation` namespace.  It provides validators and validator combinators to build up data validation functions/expressions.

2022-05-26 13:35 UTC, kaaninho requested changes

2022-05-31 07:13 UTC, neshtea commented on README.md
> +  `candidate` is between ]0 65536[."
You're right, thats way easier to understand.

2022-05-31 07:13 UTC, neshtea commented on README.md
> +  `make-config` function is curried automatically.
You're right, the user should not need to know this.

2022-05-31 07:19 UTC, neshtea commented on src/active/clojure/validation.cljc
> +  Chiefly, it provides the [[validation]] function that defines a data
I was thinking of it more as defining a value (a "validation") than of applying the validation, but maybe you're right. I would have a gripe with the other `validate-*` functions, which behave differently -- that is, they validate a candidate value.  `validation` is more of a `lift` that wraps a "normal" function into a validated one. How can we resolve this?

2022-05-31 07:21 UTC, neshtea commented on src/active/clojure/validation.cljc
> +      (let [v (validate candidate label)]
The `validate` function supplied in the arguments?  Sorry, I seem to not get the question.

2022-05-31 07:53 UTC, neshtea commented on src/active/clojure/validation.cljc
> +      (reduce mappend-validation-failure failure failures))))
Thanks for catching that.  This should be resoved in 398ad50f00f2d116cacb2eff23a7679c2f283e0e.  If there is more than one error, the "choice" failure is added to the the base failures.

2022-05-31 08:19 UTC, neshtea commented on src/active/clojure/validation.cljc
> +      (let [v (validate candidate label)]
Alright, so I will mark this as resolved then.

2022-05-31 09:55 UTC, neshtea commented on src/active/clojure/validation.cljc
> +    (validation-success? result) (fmap-success f-failure result)))
This is resolved in 1c07e52cdb6b02f286c67c01e9525df31ee26d2f.

2022-05-31 09:57 UTC, neshtea commented
> There are still "7 hidden conversations" left, did you see them, @neshtea ?

Thanks for pointing that out.  All requested changes were applied.  There is one open conversation left for you.

2022-05-31 10:09 UTC, kaaninho commented
> All requested changes were applied.

What about this one? https://github.com/active-group/active-clojure/pull/43#discussion_r882660032 ;-)

2022-05-31 12:39 UTC, kaaninho approved these changes

2022-06-01 14:07 UTC, neshtea commented on test/active/clojure/validation_test.cljc
> +                                 (v/validate-choice [v/validate-string
Fixed in 452fd4896a489a9e359bbd94e71c2584be24a4e1

2022-06-01 14:07 UTC, neshtea commented on test/active/clojure/validation_test.cljc
> +(t/deftest sequence-of-test
Fixed in 452fd4896a489a9e359bbd94e71c2584be24a4e1

2022-06-02 09:54 UTC, neshtea commented on src/active/clojure/validation.cljc
> +        (curry-n (partial f x) (dec n))))))
Nice catch.  I've added this in be151cb9d4ec4a288bb531bb2e1b490042e558e5

2022-06-02 10:10 UTC, smoes commented on src/active/clojure/validation.cljc
> +            validations)))
It is far more readable for me, but I've become an "expert" for this code already :P 
Maybe leave out `juxt`, I think that is not very popular, and use the rest? But if you think it's too clever (which can be a valid point), leave it like it is.

2022-06-02 10:12 UTC, smoes commented on src/active/clojure/validation.cljc
> +            validations)))
On the other hand, "collecting failures from multiple validations" is `validation` by definition, so maybe it isn't too clever

2022-06-07 12:03 UTC, neshtea commented on src/active/clojure/validation.cljc
> +            validations)))
I've given it some thought and think you're right. I've added this in cb1cd3a85e57fa6d6e995f324ee1a466429cd97b

2022-06-07 12:05 UTC, merged